# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 705dafcf5294ab7bb92581522fb5c6bec8760cf53dc8cc8cbfc79c923f0abf6a2f8e3b95fc10bac6ad6582fef5ec234188ab7be21e00a1d42427ce00989f6015

test:
  secret_key_base: dee7d8fd69f151f344444370ebc052be7a857e8ae7ecbf13ebda72bbb7ff9ce35f64267e715693112c1d4bbc9b6a9de8605395104409f90b8eb2a0e45da102e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
